import type { ServiceDeskData } from "./types";

const now = new Date();
const daysAgo = (d: number) => new Date(now.getTime() - d * 86400000).toISOString();

export const SEED_DATA: ServiceDeskData = {
  users: [
    {
      id: "u-admin",
      email: "admin@fixatech.com",
      name: "Sistem Yöneticisi",
      role: "admin",
      phone: "+90 533 821 61 72",
    },
    {
      id: "u-tech-1",
      email: "teknik@fixatech.com",
      name: "Ahmet Yılmaz",
      role: "technician",
      phone: "+90 532 100 20 30",
    },
    {
      id: "u-tech-2",
      email: "mehmet@fixatech.com",
      name: "Mehmet Kaya",
      role: "technician",
      phone: "+90 532 200 30 40",
    },
    {
      id: "u-customer-1",
      email: "musteri@fixatech.com",
      name: "Mehmet Yıldırım",
      role: "customer",
      phone: "+90 212 555 01 01",
      companyId: "c-1",
    },
  ],
  companies: [
    {
      id: "c-1",
      name: "Grand Bosphorus Hotel",
      contactPerson: "Mehmet Yıldırım",
      phone: "+90 212 555 01 01",
      email: "teknik@grandbosphorus.com",
      address: "Cumhuriyet Cad. No: 42",
      district: "Şişli",
      city: "İstanbul",
      type: "hotel",
    },
    {
      id: "c-2",
      name: "La Cucina Restoran",
      contactPerson: "Ayşe Korkmaz",
      phone: "+90 216 444 22 11",
      email: "isletme@lacucina.com",
      address: "Moda Cad. No: 18",
      district: "Kadıköy",
      city: "İstanbul",
      type: "restaurant",
    },
  ],
  technicians: [
    {
      id: "t-1",
      userId: "u-tech-1",
      name: "Ahmet Yılmaz",
      phone: "+90 532 100 20 30",
      email: "teknik@fixatech.com",
      specialties: ["Endüstriyel Mutfak", "Soğutma"],
      active: true,
      location: { lat: 41.04, lng: 28.98, label: "Şişli — Saha" },
    },
    {
      id: "t-2",
      userId: "u-tech-2",
      name: "Mehmet Kaya",
      phone: "+90 532 200 30 40",
      email: "mehmet@fixatech.com",
      specialties: ["Elektrik", "Su Tesisatı"],
      active: true,
      location: { lat: 41.01, lng: 29.02, label: "Kadıköy — Saha" },
    },
  ],
  tickets: [
    {
      id: "tk-1",
      code: "FIX-2026-0001",
      companyId: "c-1",
      createdByUserId: "u-customer-1",
      assignedTechnicianId: "t-1",
      status: "in_progress",
      urgency: "urgent",
      serviceMode: "onsite",
      companyName: "Grand Bosphorus Hotel",
      contactPerson: "Mehmet Yıldırım",
      phone: "+90 212 555 01 01",
      email: "teknik@grandbosphorus.com",
      address: "Cumhuriyet Cad. No: 42",
      district: "Şişli",
      city: "İstanbul",
      businessType: "hotel",
      productType: "Endüstriyel Fırın",
      productName: "Konveksiyonlu fırın",
      brand: "Rational",
      model: "SCC 101",
      serialNo: "RAT-88421",
      quantity: 1,
      issueDescription: "Fırın 180°C'ye ulaşmıyor, alarm kodu E14 görünüyor.",
      photos: [],
      videos: [],
      serviceDate: new Date().toISOString().split("T")[0],
      serviceTime: "10:00 – 12:00",
      estimatedCompletion: new Date(now.getTime() + 2 * 86400000).toISOString(),
      warrantyStatus: "yes",
      previousService: true,
      notes: "Ana mutfak girişi, güvenlikten geçiş gerekli.",
      workPerformed: "Sensör kontrolü yapıldı, kalibrasyon başlatıldı.",
      partsUsed: [{ name: "Sıcaklık sensörü", qty: 1, cost: 2400 }],
      createdAt: daysAgo(2),
      updatedAt: daysAgo(0),
    },
    {
      id: "tk-2",
      code: "FIX-2026-0002",
      companyId: "c-2",
      createdByUserId: "u-admin",
      assignedTechnicianId: "t-2",
      status: "assigned",
      urgency: "normal",
      serviceMode: "workshop",
      companyName: "La Cucina Restoran",
      contactPerson: "Ayşe Korkmaz",
      phone: "+90 216 444 22 11",
      email: "isletme@lacucina.com",
      address: "Moda Cad. No: 18",
      district: "Kadıköy",
      city: "İstanbul",
      businessType: "restaurant",
      productType: "Bulaşık Makinesi",
      productName: "Endüstriyel bulaşık makinesi",
      brand: "Electrolux",
      model: "WD-6",
      serialNo: "ELX-55201",
      quantity: 1,
      issueDescription: "Su tahliye pompası çalışmıyor.",
      photos: [],
      videos: [],
      serviceDate: new Date(now.getTime() + 86400000).toISOString().split("T")[0],
      serviceTime: "14:00 – 16:00",
      warrantyStatus: "no",
      previousService: false,
      notes: "",
      createdAt: daysAgo(1),
      updatedAt: daysAgo(1),
    },
    {
      id: "tk-3",
      code: "FIX-2026-0003",
      companyId: "c-1",
      createdByUserId: "u-customer-1",
      status: "pending",
      urgency: "critical",
      serviceMode: "onsite",
      companyName: "Grand Bosphorus Hotel",
      contactPerson: "Mehmet Yıldırım",
      phone: "+90 212 555 01 01",
      email: "teknik@grandbosphorus.com",
      address: "Cumhuriyet Cad. No: 42",
      district: "Şişli",
      city: "İstanbul",
      businessType: "hotel",
      productType: "Soğutucu",
      productName: "Soğuk oda ünitesi",
      brand: "Daikin",
      model: "VRV-III",
      serialNo: "DK-99102",
      quantity: 1,
      issueDescription: "Soğuk oda sıcaklığı +8°C'ye çıktı, acil müdahale.",
      photos: [],
      videos: [],
      serviceDate: new Date().toISOString().split("T")[0],
      serviceTime: "08:00 – 10:00",
      warrantyStatus: "unknown",
      previousService: false,
      notes: "7/24 acil hat üzerinden bildirildi.",
      createdAt: daysAgo(0),
      updatedAt: daysAgo(0),
    },
  ],
  events: [
    {
      id: "ev-1",
      ticketId: "tk-1",
      type: "status",
      message: "Kayıt oluşturuldu — Beklemede",
      createdAt: daysAgo(2),
      createdBy: "u-customer-1",
      createdByName: "Mehmet Yıldırım",
    },
    {
      id: "ev-2",
      ticketId: "tk-1",
      type: "assignment",
      message: "Ahmet Yılmaz atandı",
      createdAt: daysAgo(2),
      createdBy: "u-admin",
      createdByName: "Sistem Yöneticisi",
    },
    {
      id: "ev-3",
      ticketId: "tk-1",
      type: "status",
      message: "Durum: İşlem Yapılıyor",
      createdAt: daysAgo(1),
      createdBy: "u-tech-1",
      createdByName: "Ahmet Yılmaz",
    },
    {
      id: "ev-4",
      ticketId: "tk-1",
      type: "work",
      message: "Sensör kontrolü yapıldı, kalibrasyon başlatıldı.",
      createdAt: daysAgo(0),
      createdBy: "u-tech-1",
      createdByName: "Ahmet Yılmaz",
    },
    {
      id: "ev-5",
      ticketId: "tk-2",
      type: "status",
      message: "Kayıt oluşturuldu — Teknik Ekip Atandı",
      createdAt: daysAgo(1),
      createdBy: "u-admin",
      createdByName: "Sistem Yöneticisi",
    },
    {
      id: "ev-6",
      ticketId: "tk-3",
      type: "status",
      message: "Kritik arıza kaydı oluşturuldu — Beklemede",
      createdAt: daysAgo(0),
      createdBy: "u-customer-1",
      createdByName: "Mehmet Yıldırım",
    },
  ],
};
