/** @deprecated Import from `@/lib/service-desk/api` — Supabase veri katmanı */
export {
  fetchDeskData,
  fetchProfile,
  fetchPublicTicketByCode,
  getCompany,
  getTicket,
  getTechnician,
  getTicketEvents,
  createCustomerAccount,
  upsertCompany,
  deleteCompany,
  upsertTechnician,
  createTicket,
  deleteTicket,
  updateTicketStatus,
  assignTechnician,
  addTicketNote,
  updateTicket,
  completeTicket,
  addTicketPhoto,
  getDashboardStats,
  emptyDeskData,
} from "./api";
